package mp

// Config структура конфигурации.
type Config struct {
	// Правила замены символов (цифры/символы на буквы).
	CharReplacements map[string]string `json:"char_replacements"`
	
	// Транслитерация.
	TranslitMap map[string][]string `json:"translit_map"`
	
	// Черный список слов.
	Blacklist map[string]bool `json:"blacklist"`
	
	// Белый список слов.
	Whitelist []string `json:"whitelist"`
}

// DefaultConfig возвращает конфиг по умолчанию.
func DefaultConfig() *Config {
	return &Config{
		CharReplacements: map[string]string{
			"0": "о", "4": "ч", "3": "е", "1": "и",
			"6": "б", "7": "т", "8": "в", "9": "я", "@": "а",
			"$": "с", "+": "т", "!": "и", "№": "н",
		},
		Blacklist: map[string]bool{
			"блядина":   true,
			"бляди":     true,
			"блядь":     true,
			"блядский":  true,
			"блять":     false,
			"гандон":    true,
			"гондон":    true,
			"даун":      true,
			"долбаеб":   true,
			"долбаёб":   true,
			"долбоеб":   true,
			"долбоёб":   true,
			"дроч":			 false,
			"еба":       false,
			"ебал":      false,
			"ебала":     false,
			"ебанат":    true,
			"ебаная":    true,
			"ебаное":    true,
			"ебаный":    true,
			"ебанная":   true,
			"ебанное":   true,
			"ебанный":   true,
			"ебарь":     true,
			"ебатель":   true,
			"ебеня":     true,
			"ебирь":     true,
			"еблан":     true,
			"ебля":      true,
			"ебу":       false,
			"ебучая":    true,
			"ебучее":    true,
			"ебучие":    true,
			"ебучий":    true,
			"ебырь":     true,
			"ёб":        false,
			"ёбарь":     true,
			"жоп":			 false,
			"зигомет":   true,
			"зигомёт":   true,
			"маскаль":   true,
			"москаль":   true,
			"нахуй":     true,
			"отсос":     false,
			"отсосу":    false,
			"педик":     true,
			"пенис":     true,
			"пенисы":    true,
			"пидар":     true,
			"пидарас":   true,
			"пидор":     true,
			"пидоры":    true,
			"пидорас":   true,
			"пидорашка": true,
			"пизда":     true,
			"пиздец":    true,
			"писька":    true,
			"писюн":     true,
			"пися":      false,
			"ссать":		 true,
			"ссыш":			 false,
			"уебан":     true,
			"уебок":     true,
			"хуеглот":   true,
			"хуила":     true,
			"хуеплет":   true,
			"хуесос":    true,
			"хуем":      true,
			"хуй":       true,
			"хуе":       true,
			"хуя":       true,
			"хуйло":     true,
			"хуйня":     true,
			"чурка":     true,
			"шлюшка":    true,
			"шлюха":     true,
			"щлюха":     true,
			"blyat":     true,
			"dolboeb":   true,
			"ebani":     true,
			"eblan":     true,
			"gondon":    true,
			"huesos":    true,
			"hui":       true,
			"huy":       true,
			"nahuy":     true,
			"jopa":			 true,
			"penis":     true,
			"pidor":     true,
			"suka":			 true,
			"xyu":       true,
			"zhop":			 false,
			"\u0fd6":    true,
			"\u534d":    true,
			"\u5350":    true,
		},
		Whitelist: []string{
			"хлебать",
      "застрахуй",
			"себастьян",
			"страхуй",
		},
	}
}
