name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Закачка кода на ранер
        uses: actions/checkout@v4
      - name: Устанавливаем Гоу
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
      - name: Прогреваем кэш
        uses: actions/cache@v4
        with:
          path: |
            ~/go/bin
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-bin-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-bin-
      - name: Устанавливаем Свагер
        run: |
          if [ ! -f ~/go/bin/swagger ]; then
            go install github.com/go-swagger/go-swagger/cmd/swagger@latest
          fi
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Устанавливаем линтер
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
      - name: Скачиваем зависимости
        run: go mod download
      - name: Запускаем проверки и сборку
        run: touch .env && make b
